apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opereto-es-node
spec:
  serviceName: opereto-es
  # NOTE: This is number of nodes that we want to run, you may update this
  replicas: 3
  selector:
    matchLabels:
      app: opereto-es-cluster
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: opereto-es-cluster
    spec:
      terminationGracePeriodSeconds: 300
      initContainers:
      # This is to fix the permission on the volume. By default elasticsearch container is not run as non root user.
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_notes_for_production_use_and_defaults
      - name: fix-the-volume-permission
        image: busybox
        command:
        - sh
        - -c
        - chown -R 1000:1000 /usr/share/elasticsearch/data
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      # To increase the default vm.max_map_count to 262144
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode
      - name: increase-the-vm-max-map-count
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      # To increase the ulimit
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_notes_for_production_use_and_defaults
      - name: increase-the-ulimit
        image: busybox
        command:
        - sh
        - -c
        - ulimit -n 65536
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: tcp
        # NOTE: you can increase this resources
        resources:
          requests:
            memory: 16Gi
          limits:
            memory: 16Gi
        env:
          - name: ES_JAVA_OPTS
            valueFrom:
              configMapKeyRef:
                name: es-config
                key: ES_JAVA_OPTS

        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data

        - name: elasticsearch-yml
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
      - name: elasticsearch-yml
        configMap:
          name: es-config
          items:
          - key: elasticsearch.yml
            path: elasticsearch.yml


  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: db-ssd
      # NOTE: You can increase the storage size
      resources:
        requests:
          storage: 200Gi