apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
data:
  elasticsearch.yml: |
    cluster.name: opereto-database-cluster
    network.host: "0.0.0.0"
    bootstrap.memory_lock: false
    discovery.zen.ping.unicast.hosts: opereto-es
    discovery.zen.minimum_master_nodes: 1
  ES_JAVA_OPTS: -Xms16000m -Xmx16000m