apiVersion: v1
kind: Secret
metadata:
  name: node-cluster-storage
type: Opaque
data:
  ### AWS S3
  OPERETO_CLUSTER_STORAGE_NAME: ""
  OPERETO_CLUSTER_STORAGE_S3_AK: ""
  OPERETO_CLUSTER_STORAGE_S3_SK: ""
  OPERETO_CLUSTER_SANDBOX_STORAGE_NAME: ""
  OPERETO_CLUSTER_SANDBOX_STORAGE_S3_AK: ""
  OPERETO_CLUSTER_SANDBOX_STORAGE_S3_SK: ""


