kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: opereto
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""